### ISSUE TITLE
ImportError: No module named rospkg while building nodelet-topic-tools

### ISSUE THREAD

**Issue by kraravin** [ros/nodelet_core#84]
I am building meta-ros for ARM. Here is the build logs,

| catkin_generated/env_cached.sh /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/nodelet_core-1.9.10/nodelet_topic_tools/cfg/NodeletThrottle.cfg /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/recipe-sysroot/opt/ros/indigo/share/dynamic_reconfigure/cmake/.. /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build/devel/share/nodelet_topic_tools /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build/devel/include/nodelet_topic_tools /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build/devel/lib/python3.5/site-packages/nodelet_topic_tools
| Traceback (most recent call last):
|   File "/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/nodelet_core-1.9.10/nodelet_topic_tools/cfg/NodeletThrottle.cfg", line 3, in <module>
|     from dynamic_reconfigure.parameter_generator_catkin import *
|   File "/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/recipe-sysroot/opt/ros/indigo/lib/python3.5/site-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
|     import roslib
|   File "/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/recipe-sysroot/opt/ros/indigo/lib/python3.5/site-packages/roslib/__init__.py", line 50, in <module>
|     from roslib.launcher import load_manifest
|   File "/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/recipe-sysroot/opt/ros/indigo/lib/python3.5/site-packages/roslib/launcher.py", line 42, in <module>
|     import rospkg
| ImportError: No module named rospkg
| make[2]: *** [devel/include/nodelet_topic_tools/NodeletThrottleConfig.h] Error 1
| make[2]: Leaving directory `/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build'
| make[1]: *** [CMakeFiles/nodelet_topic_tools_gencfg.dir/all] Error 2
| make[1]: Leaving directory `/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build'
| make: *** [all] Error 2
| WARNING: /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/temp/run.do_compile.9139:1 exit 2 from 'VERBOSE=1 cmake --build '/local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/build' -- -j 20'
| ERROR: Function failed: do_compile (log file is located at /local/mnt/workspace/Automotive/LV_ROS_Build/poky/build/tmp-glibc/work/aarch64-oe-linux/nodelet-topic-tools/1.9.10-r0/temp/log.do_compile.9139)
ERROR: Task (/local/mnt/workspace/Automotive/LV_ROS_Build/poky/meta-ros/recipes-ros/nodelet-core/nodelet-topic-tools_1.9.10.bb:do_compile) failed with exit code '1'

**Comment by sloretz** [comment]
ROS 1 is end-of-life (EOL) as of today, May 31st 2025. I am archiving this repository because:

* it only supports ROS 1
* it isn't needed anymore in ROS 2

[If you still rely on ROS 1, read this page to learn about your options.](https://bit.ly/NoeticEOL)
